"""add roles table and link student_roles to roles

Revision ID: 0c563adaf00e
Revises: 699b21b0cef3
Create Date: 2025-12-26 15:25:18.378225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c563adaf00e'
down_revision = '699b21b0cef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('student_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_student_roles_role_id', 'roles', ['role_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint('fk_student_roles_role_id', type_='foreignkey')
        batch_op.drop_column('role_id')

    op.drop_table('roles')
    # ### end Alembic commands ###
