"""Add points system

Revision ID: 5e495fc9555c
Revises: b7aa9c942ec8
Create Date: 2026-01-31 13:03:13.355606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e495fc9555c'
down_revision = 'b7aa9c942ec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('is_penalty', sa.Boolean(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('point_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('som_earned', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['point_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('point_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_point_transactions_student_id'), ['student_id'], unique=False)

    # Добавляем колонки с дефолтным значением 0 для существующих записей
    op.add_column('student_profiles', sa.Column('total_points', sa.Integer(), nullable=True))
    op.add_column('student_profiles', sa.Column('total_som', sa.Integer(), nullable=True))
    
    # Устанавливаем 0 для существующих записей
    op.execute("UPDATE student_profiles SET total_points = 0 WHERE total_points IS NULL")
    op.execute("UPDATE student_profiles SET total_som = 0 WHERE total_som IS NULL")
    
    # Делаем колонки NOT NULL
    op.alter_column('student_profiles', 'total_points', nullable=False)
    op.alter_column('student_profiles', 'total_som', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_column('total_som')
        batch_op.drop_column('total_points')

    with op.batch_alter_table('point_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_point_transactions_student_id'))

    op.drop_table('point_transactions')
    op.drop_table('point_categories')
    # ### end Alembic commands ###
