"""add middle_name_and_birthday_to_student_profiles

Revision ID: e80c1e4220ff
Revises: 5e495fc9555c
Create Date: 2026-03-11 12:26:08.905321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e80c1e4220ff'
down_revision = '5e495fc9555c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('middle_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('birthday', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_column('birthday')
        batch_op.drop_column('middle_name')

    # ### end Alembic commands ###
